name: snake_border_loading
description: "Flutter Package: Snake Border Loading"
version: 0.0.2
homepage: "https://github.com/nodirbeksoliyev0811/snake_border_loading.git"
repository: "https://github.com/nodirbeksoliyev0811/snake_border_loading"
issue_tracker: "https://github.com/nodirbeksoliyev0811/snake_border_loading/issues"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
