name: snake_border_loading
description: "Flutter Package: Snake Border Loading"
version: 0.0.1
homepage: "https://github.com/nodirbeksoliyev0811/snake_border_loading.git"

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_lints: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
